name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: Build test binary
      run: |
          g++ -std=c++17 -Wall -Wextra -Werror -Wpedantic -I . \
              test.cpp functions_to_implement.cpp -o test
    - name: Run tests
      run: ./test

